AllCops:
  TargetRubyVersion: 2.7
  SuggestExtensions: false
  NewCops: enable

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

# Do it the same way net/smtp does
Style/ClassAndModuleChildren:
  Enabled: false

Metrics/BlockLength:
  Max: 40
