name: Ruby tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: matrix.os
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - "2.7.8"
          - "3.0.7"
          - "3.1.5"
          - "3.2.4"
          - "3.3.1"
        os:
          - ubuntu-20.04
          - ubuntu-22.04
          - ubuntu-24.04
          - macos-14

    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Run the default task
        run: bundle exec rake
